imgz/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("narnia/", admin.site.urls),
    path("narnia/", include("loginas.urls")),
    path("blog/", include("simpleblog.urls")),
    path("", include("main.urls")),
    path("auth/", include("tokenauth.urls", namespace="tokenauth")),
]

main/urls.py
"""The main application's URLs."""
from django.urls import path
from django.urls import re_path
from django.views.generic import TemplateView

from . import api
from . import views
from . import views_payment

app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("account/", views.account, name="account"),
    path("upload/", views.image_upload, name="image-upload"),
    path("latest/", views.latest, name="latest"),
    path("logout", views.logout, name="logout"),
    re_path(r"^(?P<image_id>i[a-zA-Z0-9]{7})/$", views.image_page, name="image-page"),
    re_path(
        r"^(?P<image_id>i[a-zA-Z0-9]{7})/delete/$",
        views.image_delete,
        name="image-delete",
    ),
    re_path(
        r"^(?P<image_id>i[a-zA-Z0-9]{7})-(?P<size>\d+)\.(?P<extension>\w+)$",
        views.image_show_resized,
        name="image-show-resized",
    ),
    re_path(
        r"^(?P<image_id>i[a-zA-Z0-9]{7})_(?P<size>\d+)\.(?P<extension>\w+)$",
        views.image_show_thumbnail,
        name="image-show-thumb",
    ),
    re_path(
        r"^(?P<image_id>i[a-zA-Z0-9]{7})\.(?P<extension>\w+)$",
        views.image_show,
        name="image-show",
    ),
]

urlpatterns += [
    path("api/image/", api.ImageView.as_view(), name="api-image"),
    path("api/image/<image_id>/", api.ImageView.as_view(), name="api-image-detail"),
]

urlpatterns += [
    path("help/faq/", TemplateView.as_view(template_name="faq.html"), name="faq"),
    path("help/api/", views.api_docs, name="api-docs"),
    path("help/terms/", TemplateView.as_view(template_name="terms.html"), name="terms"),
]

urlpatterns += [
    path("money/", TemplateView.as_view(template_name="money.html"), name="money"),
    path(
        "money-safe/",
        TemplateView.as_view(template_name="money-safe.html"),
        name="money-safe",
    ),
    path("money/stripe/", views_payment.stripe_redirect, name="stripe-redirect"),
    path("money/stripe/webhook/", views_payment.stripe_webhook, name="stripe-webhook"),
    path("money/cryptocurrency/", views_payment.btc_redirect, name="btc-redirect"),
    path(
        "money/cryptocurrency/webhook/", views_payment.btc_webhook, name="btc-webhook"
    ),
    path(
        "money/thanks/",
        TemplateView.as_view(template_name="thanks.html"),
        name="payment-return",
    ),
]

simpleblog/urls.py
try:
    from django.urls import re_path
except ModuleNotFoundError:
    from django.conf.urls import url as re_path

from .views import BlogDetailView
from .views import BlogListView
from .views import LatestEntriesFeed

urlpatterns = [
    re_path(
        r"^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-_\w]+)/$",
        BlogDetailView.as_view(),
        name="blog_detail",
    ),
    re_path(
        r"^archive/$",
        BlogListView.as_view(
            template_name="simpleblog/post_archive.html",
            page_template="simpleblog/post_archive_page.html",
        ),
        name="blog_archive",
    ),
    re_path(r"^latest/feed/$", LatestEntriesFeed()),
    re_path(r"^$", BlogListView.as_view(), name="blog_index"),
]

main/views.py
import datetime
from typing import Optional

from django import forms
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.http import HttpRequest
from django.http import HttpResponse
from django.http import HttpResponseNotFound
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.views.decorators.http import require_POST
from loginas.utils import restore_original_login

from .models import Image
from .models import User
from .utils import process_upload
from .utils import resize_image
from .utils import UploadError


def get_image(image_id: str) -> Image:
    image = get_object_or_404(Image, pk=image_id)
    return image


def delete_all_their_shit(user: User) -> None:
    """
    Delete all the user's shit.
    """
    for image in Image.objects.filter(user=user):
        image.delete()

    user.upgraded_until = datetime.date(2000, 1, 1)
    user.storage_space = 0
    user.bonus_space = 0
    user.save()


@login_required
def logout(request):
    """
    Log the user out.

    This is a custom logout view that restores the original user with django-loginas.
    """
    restore_original_login(request)
    return redirect(settings.LOGOUT_REDIRECT_URL)


@login_required
def account(request):
    if request.method == "POST":
        if request.GET.get("delete") == "allmyshit":
            delete_all_their_shit(request.user)
            messages.success(request, "Good riddance.")
            logout(request)
        return redirect("main:index")

    return render(request, "account.html")


def api_docs(request: HttpRequest) -> HttpResponse:
    api_key = request.user.api_key if request.user.is_authenticated else "y0uRAP1k3y"
    return render(request, "api.html", {"api_key": api_key})


def latest(request: HttpRequest) -> HttpResponse:
    if not request.user.is_superuser:
        raise Http404()
    return render(
        request, "latest.html", {"images": Image.objects.order_by("-uploaded")[:50]}
    )


def index(request: HttpRequest) -> HttpResponse:
    if not request.user.is_authenticated:
        if request.GET.get("v") == "s":
            return render(request, "simple_landing.html")
        elif request.GET.get("v") == "c":
            return render(request, "complex_landing.html")
        else:
            return render(request, "index.html")

    if not request.user.is_upgraded:
        return render(request, "unpaid.html")

    return render(
        request, "home.html", {"images": request.user.images.order_by("-uploaded")}
    )


def image_show_resized(
    request: HttpRequest, image_id: str, size: str, extension: Optional[str] = None
) -> HttpResponse:
    """
    Show a resized image.
    """
    image = get_image(image_id)
    s = int(size)
    if s != 1280:
        return HttpResponseNotFound("Size not found.")

    data = resize_image(image.data, s)
    response = HttpResponse(data, content_type=f"image/{image.format}")
    response["Content-Length"] = len(data)
    return response


def image_show_thumbnail(
    request: HttpRequest, image_id: str, size: str, extension: Optional[str] = None
) -> HttpResponse:
    """
    Show an image's thumbnail.
    """
    image = get_image(image_id)
    s = int(size)
    if s != 512:
        return HttpResponseNotFound("Thumbnail not found.")

    # We're going to do this on the fly and rely on caching to save the day.
    data = bytes(image.thumbnail_512)
    response = HttpResponse(data, content_type=f"image/{image.format}")
    response["Content-Length"] = len(data)
    return response


def image_page(
    request: HttpRequest, image_id: str, extension: Optional[str] = None
) -> HttpResponse:
    """
    Show an image page.
    """
    image = get_image(image_id)

    if request.method == "POST":
        if image.user != request.user:
            messages.error(request, "No.")
            return redirect(image)

        try:
            image.set_title(request.POST.get("title"))
        except ValueError as e:
            messages.error(request, str(e))
            return redirect(image)

        image.save()
        messages.success(
            request, "The previous title sucked, huh? Well this one isn't any better."
        )
        return redirect(image)

    image.increment_views()
    return render(
        request, "image.html", {"image": image, "nopreview": request.GET.get("np")}
    )


def image_show(
    request: HttpRequest, image_id: str, extension: Optional[str] = None
) -> HttpResponse:
    """
    Show a bare image.
    """
    image = get_image(image_id)
    # We cast to bytes here because this is a memoryview on Postgres
    # but just bytes on SQLite.
    data = bytes(image.data)
    response = HttpResponse(data, content_type=f"image/{image.format}")
    response["Content-Length"] = len(data)
    return response


@login_required
@require_POST
def image_delete(
    request: HttpRequest, image_id: str, extension: Optional[str] = None
) -> HttpResponse:
    image = get_image(image_id)
    if image.user != request.user and not request.user.is_superuser:
        raise Http404
    image.delete()
    messages.success(request, "Okay, the image is gone. It was a dick pic, wasn't it?")
    return redirect("main:index")


@login_required
def image_upload(request: HttpRequest) -> HttpResponse:
    class ImageUploadForm(forms.Form):
        EXPIRATION = [
            [10, "ten minutes"],
            [60, "an hour"],
            [24 * 60, "a day"],
            [7 * 24 * 60, "a week"],
            [14 * 24 * 60, "two weeks"],
            [30 * 24 * 60, "a month"],
            [None, "never"],
        ]

        title = forms.CharField(
            max_length=200, help_text="The title of the image.", required=False
        )
        expires = forms.ChoiceField(
            choices=EXPIRATION, initial=None, label="Expires in", required=False
        )

        image = forms.FileField()

    if request.method == "POST":
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                image = process_upload(
                    request.FILES,
                    request.user,
                    title=form.cleaned_data["title"],
                    expires_in=int(form.cleaned_data["expires"])
                    if form.cleaned_data["expires"]
                    else None,
                )
            except UploadError as e:
                messages.error(request, str(e))
                return redirect("main:image-upload")
            else:
                return redirect(image)
    else:
        form = ImageUploadForm()
    return render(request, "upload.html", {"form": form})

templates/account.html
{% extends "base.html" %}

{% load human_size %}

{% block title %}Your account{% endblock %}

{% block content %}
  	<!--begin services section -->
    <section class="section-grey section-top-border" id="features">

        <!--begin container -->
        <div class="container">

            <!--begin row -->
            <div class="row">

                <!--begin col-md-12-->
                <div class="col-md-8 offset-md-2 text-center padding-bottom-10">
                    <h2 class="section-title">
                        Stuff about your account
                    </h2>

                    {% if request.user.is_upgraded %}
                    <p class="section-subtitle" style="margin-top: 60px">
                    You're using
                    {{ request.user.total_space_taken|human_size }} / {{ request.user.total_space|human_size }} of space
                    and your
                    {% if request.user.has_ever_paid %}
                        subscription expires
                    {% else %}
                        free trial ends
                    {% endif %}
                        on {{ request.user.upgraded_until }}.
                    </p>

                    <p>
                    {% if not request.user.has_ever_paid %}
                    Also, all your images will be deleted after your trial ends,
                    <br> so make sure you pay!
                    {% endif %}
                    </p>

                    <h4>API</h4>
                    <p>
                    If you want to use the API, your <code>api_key</code> is
                    <code>{{ request.user.api_key }}</code>.
                    </p>

                    {% if request.user.has_ever_paid %}
                    <h4>Subscription stuff</h4>

                    <p>
                    If you're paying for a subscription and want to cancel, I haven't written that code yet. Contact me
                    or wait, like, two days.
                    </p>
                    {% endif %}
                    {% endif %}

                    <h4>Delete your account</h4>

                    <p>
                    You think I'm going to try to dissuade you? I don't even <strong>want</strong> you here!

                    <form
                        onsubmit="return confirm('Are you sure you want to delete all your shit? I\'m only asking for liability purposes.');"
                        method="post" action="{% url "main:account" %}?delete=allmyshit">
                        <button type="submit" class="btn btn-danger">Delete all my shit</button>
                    </form>
                    </p>
                </div>
                <!--end col-md-12 -->

            </div>
            <!--end row -->

        </div>
        <!--end container -->

    </section>
    <!--end services section -->
{% endblock %}

templates/analytics.html
{% if not settings.DEBUG %}
<noscript><img src="https://nsa.stavros.io/ingress/de5a9062-c300-4065-88c9-14e5cf1c182b/pixel.gif"></noscript>
<script src="https://nsa.stavros.io/ingress/de5a9062-c300-4065-88c9-14e5cf1c182b/script.js"></script>
{% endif %}

templates/api.html
{% extends "base.html" %}

{% load human_size %}

{% block title %}Frequently asked questions{% endblock %}

{% block content %}
  	<!--begin services section -->
    <section class="section-grey section-top-border" id="features">

        <!--begin container -->
        <div class="container">

            <!--begin row -->
            <div class="row">

                <!--begin col-md-8-->
                <div class="col-md-8 offset-md-2 text-center padding-bottom-10 left-text">
                    <h3>API documentation</h3>

                    <p>
                    Ugh, I didn't want to go into all this detail, but it's not like anyone is going to look at the
                    publicly-available, amply-documented, simple code to figure out how the API works, so here we are.
                    </p>

                    <p>
                    The API is pretty RESTful and non-surprising, you authenticate with your API key and it's all good.
                    </p>


                    <h4>Authentication</h4>

                    <p>
                    Authentication is easy enough that even you can do it. Just use your API key as your password in
                    HTTP Basic auth.
                    </p>


                    <h4>Uploading an image</h4>

                    <p>
                    To upload an image, simply <code>POST</code> to
                    <code>https://{{ request.site.domain }}{% url "main:api-image" %}</code> as a
                    <code>multipart/form-data</code> content type, with your image in the <code>image</code> field and
                    the title in the <code>title</code> field.<br>
                    You can also set the <code>expires_in</code> field to the number of minutes you want the image to
                    expire in.
                    </p>

                    <p>
                    Example:
                    </p>

                    <p>
                    <code>
                        curl https://:{{ api_key }}@{{ request.site.domain }}{% url "main:api-image" %} \<br>
                            &nbsp;&nbsp;&nbsp;-F "image=@/some/image/path.png" \<br>
                            &nbsp;&nbsp;&nbsp;-F "title=I am alone."
                    </code>
                    </p>


                    <h4>Retrieving an image</h4>

                    <p>
                    This doesn't even need auth. Just make a <code>GET</code> request to
                    <code>https://:{{ api_key }}@{{ request.site.domain }}{% url "main:api-image-detail" "image_id" %}</code>
                    </p>

                    <p>
                    Example:
                    </p>

                    <p>
                    <code>
                        curl https://{{ request.site.domain }}{% url "main:api-image-detail" "iJKuc6HA" %}
                    </code>
                    </p>

                    <h4>Editing an image</h4>

                    <p>
                    To edit an image, <code>PUT</code> to
                    <code>https://{{ request.site.domain }}{% url "main:api-image-detail" "image_id" %}</code>.
                    You can currently only change the title by passing the <code>title</code> field. The request should
                    be JSON-encoded with the appropriate content type.
                    </p>

                    <p>
                    Example:
                    </p>

                    <p>
                    <code>
                        curl https://:{{ api_key }}@{{ request.site.domain }}{% url "main:api-image-detail" "iJKuc6HA" %} \<br>
                        &nbsp;&nbsp;&nbsp;-H 'Content-Type: application/json' -X PUT -d '{"title": "This is me."}'
                    </code>
                    </p>

                    <h4>Deleting an image</h4>

                    <p>
                    Unsurprisingly, <code>DELETE</code> to
                    <code>https://{{ request.site.domain }}{% url "main:api-image-detail" "image_id" %}</code>.
                    </p>

                    <p>
                    Example:
                    </p>

                    <p>
                    <code>
                        curl -X DELETE https://:{{ api_key }}@{{ request.site.domain }}{% url "main:api-image-detail" "iJKuc6HA" %}
                    </code>
                    </p>
                </div>
                <!--end col-md-12 -->

            </div>
            <!--end row -->

        </div>
        <!--end container -->

    </section>
    <!--end services section -->
{% endblock %}

templates/base.html
{% load i18n staticfiles %}<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="">
    <meta name="description" content="">

    <title>{% block title %}Image sharing. No bullshit.{% endblock %} - {{ request.site.name }}</title>

    <!-- Loading Bootstrap -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <link href="{% static "css/all.min.css" %}" rel="stylesheet">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Dosis:500,600" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300i,400,400i,600,700" rel="stylesheet">

    <!-- favicons -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "images/icons/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" href="{% static "images/icons/favicon-32x32.png" %}" sizes="32x32">
    <link rel="icon" type="image/png" href="{% static "images/icons/favicon-16x16.png" %}" sizes="16x16">
    <link rel="manifest" href="{% static "images/icons/site.webmanifest" %}">
    <link rel="mask-icon" href="{% static "images/icons/safari-pinned-tab.svg" %}" color="#33759F">
    <link rel="shortcut icon" href="{% static "images/icons/favicon.ico" %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-config" content="{% static "images/icons/browserconfig.xml" %}">
    <meta name="theme-color" content="#ffffff">

    {% if image and not nopreview %}
    <link rel="canonical" href="https://{{ request.site.domain }}{{ image.get_absolute_url }}" />

    <meta property="og:title" content="{{ image.title }}">
    <meta property="og:site_name" content="{{ request.site.name }}">
    <meta property="og:url" content="https://{{ request.site.domain }}{{ image.get_absolute_url }}">
    <meta property="og:description" content="A sublime image, viewed {{ image.views }} times.">
    <meta property="og:type" content="object">
    <meta property="og:image" content="https://{{ request.site.domain }}{{ image.get_thumbnail_url }}">
    <meta property="og:image:width" content="512">
    <meta property="og:image:height" content="512">
    {% else %}
    <meta property="og:title" content="Image sharing. No bullshit.">
    <meta property="og:site_name" content="{{ request.site.name }}">
    <meta property="og:url" content="https://{{ request.site.domain }}">
    <meta property="og:description" content="{{ request.site.name}} shares images.">
    <meta property="og:type" content="object">
    <meta property="og:image" content="https://{{ request.site.domain }}{% static "images/icons/android-chrome-512x512.png" %}">
    <meta property="og:image:width" content="512">
    <meta property="og:image:height" content="512">
    {% endif %}

    <script>
        window.addEventListener('DOMContentLoaded', (event) => {
            [...document.querySelectorAll('[data-toggle]')].forEach((toggler) => {
                toggler.addEventListener('click', function(e) {
                    document.querySelector(this.dataset.target).classList.toggle('show');
                });
            });
        });
    </script>
    {% block head %}
    {% endblock %}
</head>

<body class="{% block page-class %}{% endblock %}">
    <!--begin header -->
    <header class="header">

        <!--begin navbar-fixed-top -->
        <nav class="navbar navbar-default navbar-fixed-top">

            <!--begin container -->
            <div class="container">

                <!--begin navbar -->
                <nav class="navbar navbar-expand-lg">

                    <!--begin logo -->
                    <a class="navbar-brand" href="/"><img src="{% static "images/logo.png" %}"/> {{ request.site.name }}</a>
                    <!--end logo -->

                    <!--begin navbar-toggler -->
                    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"><i class="fas fa-bars"></i></span>
                    </button>
                    <!--end navbar-toggler -->

                    <!--begin navbar-collapse -->
                    <div class="navbar-collapse collapse" id="navbarCollapse" style="">

                        <!--begin navbar-nav -->
                        <ul class="navbar-nav ml-auto">

                            {% if request.user.is_authenticated %}
                            <li><a href="{% url "main:faq" %}">FAQ</a></li>
                            {% if not user.is_paying %}
                            <li><a href="{% url "main:money" %}">Money</a></li>
                            {% endif %}
                            <li><a href="{% url "main:image-upload" %}">Upload</a></li>
                            <li><a href="{% url "main:account" %}">Account</a></li>
                            <li><a href="{% url "main:logout" %}">Log out</a></li>
                            {% else %}
                            <li><a href="{% url "main:faq" %}">FAQ</a></li>
                            <li><a href="{% url "main:money" %}">Money</a></li>
                            <li class="discover-link"><a href="/#login" class="external discover-btn">Log in</a></li>
                            {% endif %}

                        </ul>
                        <!--end navbar-nav -->

                    </div>
                    <!--end navbar-collapse -->

                </nav>
                <!--end navbar -->

            </div>
    		<!--end container -->

        </nav>
    	<!--end navbar-fixed-top -->

    </header>
    <!--end header -->

    <div class="stupid-separator"></div>

    {% if messages %}
    <section class="section-white" style="padding: 20px 0 0px 0">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="benefits">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}><i class="fa fa-circle-notch"></i> {{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    </section>
    {% endif %}

{% block content %}
{% endblock %}

    <!--begin footer -->
    <div class="footer">

        <!--begin container -->
        <div class="container">

            <!--begin row -->
            <div class="row">

                <!--begin col-md-12 -->
                <div class="col-md-12 text-center">

                    <p>
                    Made by <a href="https://www.stavros.io" target="new">Stavros</a>
                    |
                    <a href="{% url "main:api-docs" %}">API</a>
                    |
                    <a href="{% url "main:terms" %}">Terms and conditions</a>
                    </p>

                    <ul class="footer_contact">
                        <li><a href="mailto:hi@stavros.io?subject={{ request.site.name }}+questions"><i class="fas fa-envelope"></i></a></li>
                        <li><a href="https://twitter.com/stavros"><i class="fab fa-twitter"></i></a></li>
                    </ul>

                </div>
                <!--end col-md-6 -->

            </div>
            <!--end row -->

        </div>
        <!--end container -->

    </div>

{% include "analytics.html" %}
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}Your images{% endblock %}

{% block content %}
  	<!--begin services section -->
    <section class="section-grey section-top-border" id="features">

        <!--begin container -->
        <div class="container">

            <!--begin row -->
            <div class="row">

                <!--begin col-md-12-->
                <div class="col-md-12 text-center padding-bottom-10">
                    <h3>Your images</h3>

                    <div class="row">
                        {% for image in images %}
                            {% include "fragments/image_card.html" %}
                        {% empty %}
                        <div class="col-md-12">
                        <p style="text-align: center">
                        You have no images. What's the use of an image sharing service with no images? Go <a
                            href="{% url "main:image-upload" %}">upload some</a>!
                        </p>
                        </div>
                        {% endfor %}
                    </div>

                </div>
                <!--end col-md-12 -->

            </div>
            <!--end row -->

        </div>
        <!--end container -->

    </section>
    <!--end services section -->
{% endblock %}

templates/money-safe.html
{% extends "base.html" %}

{% load staticfiles human_size %}

{% block title %}Buy my wares{% endblock %}

{% block content %}

{% if stripe_session_id %}
<script src="https://js.stripe.com/v3/"></script>

<script>
    var stripe = Stripe('{{ settings.STRIPE_PUBLIC_KEY }}');

    stripe.redirectToCheckout({
      sessionId: '{{ stripe_session_id }}'
    }).then(function (result) {
      alert(result.error.message);
    });
</script>
{% endif %}

<section class="section-grey" id="pricing">

<!--begin container -->
<div class="container">

    <!--begin row -->
    <div class="row">

        <!--begin col-md-12 -->
        <div class="col-md-8 offset-md-2 text-center padding-bottom-40">

            <h2 class="section-title">Funds</h2>

            {% if not request.user.is_paying %}
            <p class="section-subtitle">
            Here you can purchase our services.
            </p>
            {% else %}
            <p class="section-subtitle">
            You've already paid, there's nothing for you here.
            </p>
            {% endif %}

        </div>
        <!--end col-md-12 -->

        {% if not request.user.is_paying %}
        <!--begin col-lg-3-->
        <div class="col-lg-3">

            <div class="price-box">

                <ul class="pricing-list">

                    <li class="price-title white-text">CHEAP</li>

                    <li class="price-value white-text">$5</li>

                    <li class="price-subtitle white-text">Per Year</li>

                    <li class="price-text"><i class="fas fa-check blue"></i><strong>1 GB</strong></li>

                    <li class="price-text"><i class="fas fa-check blue"></i>Nothing else</li>

                    <li class="price-tag-line"><a href="{% url "main:stripe-redirect" %}?plan=1GB">RENT NOW</a></li>
                    <p><a href="{% url "main:btc-redirect" %}"><img src="{% static "images/btc.png" %}"></a></p>

                </ul>

            </div>

        </div>
        <!--end col-lg-3 -->

        <!--begin col-lg-3-->
        <div class="col-lg-3">

            <div class="price-box">


                <ul class="pricing-list">

                    <li class="price-title white-text">PERSON</li>

                    <li class="price-value white-text">$50</li>

                    <li class="price-subtitle white-text">Per Year</li>

                    <li class="price-text"><i class="fas fa-check blue"></i><strong>50 GB</strong></li>

                    <li class="price-text"><i class="fas fa-check blue"></i>Still cheap</li>

                    <li class="price-tag-line"><a href="{% url "main:stripe-redirect" %}?plan=50GB">RENT NOW</a></li>

                </ul>

            </div>

        </div>
        <!--end col-lg-3 -->

        <!--begin col-lg-3-->
        <div class="col-lg-3">

            <div class="price-box">

                <ul class="pricing-list">

                    <li class="price-title white-text">AESTHETE</li>

                    <li class="price-value white-text">$400</li>

                    <li class="price-subtitle white-text">Per Year</li>

                    <li class="price-text white-text"><i class="fas fa-check blue"></i><strong>500 GB</strong></li>

                    <li class="price-text"><i class="fas fa-check blue"></i>More images</li>

                    <li class="price-tag-line"><a href="{% url "main:stripe-redirect" %}?plan=500GB">RENT NOW</a></li>

                </ul>

            </div>

        </div>
        <!--end col-lg-3 -->

        <div class="col-lg-3">

            <div class="price-box">

                <div class="ribbon blue"><span>Our choice</span></div>
                <ul class="pricing-list">

                    <li class="price-title white-text">BUY THE SITE</li>

                    <li class="price-value white-text">$999,999.98</li>

                    <li class="price-subtitle white-text">Per Year</li>

                    <li class="price-text white-text"><i class="fas fa-check blue"></i><strong>1 GB</strong></li>

                    <li class="price-text"><i class="fas fa-check blue"></i>Hello.</li>

                    <li class="price-text"><i class="fas fa-check blue"></i>Still no support</li>

                    <li class="price-tag-line"><a href="{% url "main:stripe-redirect" %}?plan=ALLOFIT">BUY NOW</a></li>

                </ul>

            </div>

        </div>
        <!--end col-lg-3 -->
        {% endif %}
    </div>
    <!--end row -->

</div>
<!--end container -->

</section>
{% endblock %}